  let ing_ok = toscalar(
    fn_src_pipeline_runs_all(startTime - 60m, endTime)
    | where ResourceGroup == "MLP-PRD-RG-BLKGRDE" // filtro temprano por dominio
    | where Category == "PipelineRuns"
    | where OperationName has "Succeeded"
    | count
  ) > 0;
  let lag = fn_prd_ada_alert_from_tables_lag(dynamic(["blockgrade_bybucket"]), startTime, endTime);
  let status = iff(not(ing_ok) or lag == "ALERT", "ALERT", "OK");
  print color = fn_mon_status_to_color(status)
