  let job = fn_mon_alert_from_job_success_src_v2(workspace("/subscriptions/c68213bf-7453-4ba4-9aaa-56b822af4c20/resourceGroups/MLP-PRD-RG-PLANS/providers/Microsoft.OperationalInsights/workspaces/mlp-prd-law-plans").table("ContainerAppSystemLogs_CL"), "mlp-prd-caj-plans-job01", 25, startTime, endTime);
  let lag = fn_prd_ada_alert_from_tables_lag(dynamic([
      "planes_semanales_AXB","planes_semanales_PLANTA_CONCENTRADORA_RECUPERACION_CU","planes_semanales_LEY_CONCENTRADO_CU",
      "planes_semanales_TRANSPORTADO_STMG","planes_semanales_CONCENTRADO_PRODUCIDO","planes_semanales_PLANTA_CONCENTRADORA_LEY_CU",
      "planes_semanales_PLANTA_CONCENTRADORA_CU_FINO_PRODUCIDO","planes_semanales_PLANTA_CONCENTRADORA_MO_FINO_PRODUCIDO",
      "planes_semanales_PLANTA_CONCENTRADORA_TRATAMIENTO","planes_semanales_PUERTO_CU_FINO_FILTRADO_PAGABLE",
      "planes_acc_mensuales_TRANSPORTADO_STMG","planes_acc_mensuales_CONCENTRADO_PRODUCIDO","planes_acc_mensuales_PLANTA_CONCENTRADORA_LEY_CU",
      "planes_acc_mensuales_LEY_CONCENTRADO_CU","planes_acc_mensuales_PUERTO_CU_FINO_FILTRADO_PAGABLE",
      "planes_acc_mensuales_PLANTA_CONCENTRADORA_TRATAMIENTO","planes_acc_mensuales_EXTRACCION_MINA",
      "planes_acc_mensuales_PLANTA_CONCENTRADORA_CU_FINO_PRODUCIDO","planes_acc_mensuales_PLANTA_CONCENTRADORA_MO_FINO_PRODUCIDO",
      "planes_acc_mensuales_PLANTA_CONCENTRADORA_RECUPERACION_CU"
  ]), startTime, endTime);
  let status = iff(job == "ALERT" or lag == "ALERT", "ALERT", "OK");
  print color = fn_mon_status_to_color(status)
