<<<<<<<< HEAD:refactor_ada_optimized/law_functions_body_only/sources/fn_src_mlp_ws_plans.kql
  workspace("/subscriptions/c68213bf-7453-4ba4-9aaa-56b822af4c20/resourceGroups/MLP-PRD-RG-PLANS/providers/Microsoft.OperationalInsights/workspaces/mlp-prd-law-plans").table(tableName)
  | where TimeGenerated between (startTime .. endTime)
========
  fn_src_mlp_ws_plans("ContainerAppSystemLogs_CL", startTime, endTime)
  | project TimeGenerated, JobName_s, Type_s, Reason_s, Log_s
>>>>>>>> main:refactor_ada_optimized/law_functions_body_only/sources/fn_src_mlp_ws_plans_systemlogs.kql
