
  union isfuzzy=true
    (
      workspace("/subscriptions/c68213bf-7453-4ba4-9aaa-56b822af4c20/resourceGroups/MLP-PRD-RG-ADA/providers/Microsoft.OperationalInsights/workspaces/mlp-prd-law-ada").table("ContainerAppConsoleLogs_CL")
      | where TimeGenerated between (startTime .. endTime)
      | where sourceType == "ContainerAppConsoleLogs_CL"
      | extend source_table = "ContainerAppConsoleLogs_CL"
    ),
    (
      workspace("/subscriptions/c68213bf-7453-4ba4-9aaa-56b822af4c20/resourceGroups/MLP-PRD-RG-ADA/providers/Microsoft.OperationalInsights/workspaces/mlp-prd-law-ada").table("ContainerAppSystemLogs_CL")
      | where TimeGenerated between (startTime .. endTime)
      | where sourceType == "ContainerAppSystemLogs_CL"
      | extend source_table = "ContainerAppSystemLogs_CL"
    ),
    (
      workspace("/subscriptions/c68213bf-7453-4ba4-9aaa-56b822af4c20/resourceGroups/MLP-PRD-RG-ADA/providers/Microsoft.OperationalInsights/workspaces/mlp-prd-law-ada").table("AppServiceConsoleLogs")
      | where TimeGenerated between (startTime .. endTime)
      | where sourceType == "AppServiceConsoleLogs"
      | extend source_table = "AppServiceConsoleLogs"
    )
