let fn_src_mlp_ssag_systemlogs_all = (startTime:datetime, endTime:datetime) {
  union
    (workspace("/subscriptions/c68213bf-7453-4ba4-9aaa-56b822af4c20/resourceGroups/MLP-PRD-RG-SSAG/providers/Microsoft.OperationalInsights/workspaces/mlp-prd-law-ssag").table("ContainerAppSystemLogs_CL")
      | where TimeGenerated between (startTime .. endTime)
      | project TimeGenerated, JobName_s, Type_s, Reason_s, Log_s),
    (workspace("/subscriptions/c68213bf-7453-4ba4-9aaa-56b822af4c20/resourceGroups/MLP-PRD-RG-PLANS/providers/Microsoft.OperationalInsights/workspaces/mlp-prd-law-plans").table("ContainerAppSystemLogs_CL")
      | where TimeGenerated between (startTime .. endTime)
      | project TimeGenerated, JobName_s, Type_s, Reason_s, Log_s),
    (workspace("/subscriptions/c68213bf-7453-4ba4-9aaa-56b822af4c20/resourceGroups/MLP-PRD-RG-PDMSAGI/providers/Microsoft.OperationalInsights/workspaces/mlp-prd-law-pdmsagi").table("ContainerAppSystemLogs_CL")
      | where TimeGenerated between (startTime .. endTime)
      | project TimeGenerated, JobName_s, Type_s, Reason_s, Log_s),
    (workspace("/subscriptions/c68213bf-7453-4ba4-9aaa-56b822af4c20/resourceGroups/MLP-PRD-RG-PISYSTEM/providers/Microsoft.OperationalInsights/workspaces/mlp-prd-law-pisystem").table("ContainerAppSystemLogs_CL")
      | where TimeGenerated between (startTime .. endTime)
      | project TimeGenerated, JobName_s, Type_s, Reason_s, Log_s)
};
