  let adaJobsKpiAlert = toscalar(
    fn_prd_mlp_ada_jobs_status_detail(startTime, endTime)
    | where domain == "KPIs"
    | summarize alertCount = countif(isAlert == true)
    | project alertCount > 0
  );
  let count_no_esperados = toscalar(
    fn_prd_mlp_ada_kpi_alert_rows(endTime - 180m, endTime)
    | summarize c = dcount(KPINoEsperado)
    | project c
  );
  let status = iff(adaJobsKpiAlert or count_no_esperados > 0, "ALERT", "OK");
  print color = fn_mon_status_to_color(status)
