let fn_mon_alert_from_pipeline_success = (workspace_id:string, resource_group:string, lookback_min:int, startTime:datetime, endTime:datetime) {
  let ok = toscalar(
    workspace(workspace_id).table("AzureDiagnostics")
    | where TimeGenerated between (startTime - totimespan(lookback_min * 60s) .. endTime)
    | where Category == "PipelineRuns"
    | where ResourceGroup == resource_group
    | where OperationName has "Succeeded"
    | count
  ) > 0;
  iff(ok, "OK", "ALERT")
};
