let fn_prd_mlp_ada_dom_front_status = (startTime:datetime, endTime:datetime) {
  let has_alert = toscalar(
    fn_src_mlp_ws_ada("AppServiceConsoleLogs", endTime - 10m, endTime)
    | where TimeGenerated between (endTime - 10m .. endTime)
    | where (Level == "Error" and ResultDescription contains "/usr/src/app/app/") or ResultDescription contains "Invalid access token"
    | count
  ) > 0;
  print color = fn_mon_status_to_color(iff(has_alert, "ALERT", "OK"))
};
