let fn_prd_mlp_ada_dom_plans_status = (startTime:datetime, endTime:datetime) {
  let job_ok = toscalar(
    fn_src_mlp_systemlogs_all(startTime - 25m, endTime)
    | where JobName_s == "mlp-prd-caj-plans-job01" // filtro temprano por dominio
    | where Log_s contains "has successfully completed"
    | count
  ) > 0;
  let lag = fn_prd_mlp_ada_lag_helpers(dynamic([
      "planes_semanales_AXB","planes_semanales_PLANTA_CONCENTRADORA_RECUPERACION_CU","planes_semanales_LEY_CONCENTRADO_CU",
      "planes_semanales_TRANSPORTADO_STMG","planes_semanales_CONCENTRADO_PRODUCIDO","planes_semanales_PLANTA_CONCENTRADORA_LEY_CU",
      "planes_semanales_PLANTA_CONCENTRADORA_CU_FINO_PRODUCIDO","planes_semanales_PLANTA_CONCENTRADORA_MO_FINO_PRODUCIDO",
      "planes_semanales_PLANTA_CONCENTRADORA_TRATAMIENTO","planes_semanales_PUERTO_CU_FINO_FILTRADO_PAGABLE",
      "planes_acc_mensuales_TRANSPORTADO_STMG","planes_acc_mensuales_CONCENTRADO_PRODUCIDO","planes_acc_mensuales_PLANTA_CONCENTRADORA_LEY_CU",
      "planes_acc_mensuales_LEY_CONCENTRADO_CU","planes_acc_mensuales_PUERTO_CU_FINO_FILTRADO_PAGABLE",
      "planes_acc_mensuales_PLANTA_CONCENTRADORA_TRATAMIENTO","planes_acc_mensuales_EXTRACCION_MINA",
      "planes_acc_mensuales_PLANTA_CONCENTRADORA_CU_FINO_PRODUCIDO","planes_acc_mensuales_PLANTA_CONCENTRADORA_MO_FINO_PRODUCIDO",
      "planes_acc_mensuales_PLANTA_CONCENTRADORA_RECUPERACION_CU"
  ]), startTime, endTime);
  let status = iff(not(job_ok) or lag == "ALERT", "ALERT", "OK");
  print status = status
};
