let fn_prd_ada_dom_meteodata_status = (startTime:datetime, endTime:datetime) {
  let job01 = fn_prd_ada_alert_from_job_success("/subscriptions/c68213bf-7453-4ba4-9aaa-56b822af4c20/resourceGroups/MLP-PRD-RG-METEO/providers/Microsoft.OperationalInsights/workspaces/mlp-prd-law-meteo", "mlp-prd-caj-meteo-job01", 35, startTime, endTime);
  let job02 = fn_prd_ada_alert_from_job_success("/subscriptions/c68213bf-7453-4ba4-9aaa-56b822af4c20/resourceGroups/MLP-PRD-RG-METEO/providers/Microsoft.OperationalInsights/workspaces/mlp-prd-law-meteo", "mlp-prd-caj-meteo-job02", 35, startTime, endTime);
  let lag = fn_prd_ada_alert_from_tables_lag(dynamic(["meteodata"]), startTime, endTime);
  let status = iff(job01 == "ALERT" or job02 == "ALERT" or lag == "ALERT", "ALERT", "OK");
  print color = fn_mon_status_to_color(status)
};
