<<<<<<<< HEAD:refactor_ada_optimized/law_functions/sources/fn_src_mlp_ws_ada.kql
let fn_src_mlp_ws_ada = (tableName:string, startTime:datetime, endTime:datetime) {
  workspace("/subscriptions/c68213bf-7453-4ba4-9aaa-56b822af4c20/resourceGroups/MLP-PRD-RG-ADA/providers/Microsoft.OperationalInsights/workspaces/mlp-prd-law-ada").table(tableName)
  | where TimeGenerated between (startTime .. endTime)
========
let fn_src_mlp_ws_ada_table = (tableName:string, startTime:datetime, endTime:datetime) {
  fn_src_mlp_ws_ada(tableName, startTime, endTime)
>>>>>>>> main:refactor_ada_optimized/law_functions/sources/fn_src_mlp_ws_ada_table.kql
};
