let fn_src_mlp_pipeline_runs_all = (startTime:datetime, endTime:datetime) {
  union
    (fn_src_mlp_ws_dispatch("AzureDiagnostics", startTime, endTime) | project TimeGenerated, Category, ResourceGroup, OperationName),
    (fn_src_mlp_ws_drillit("AzureDiagnostics", startTime, endTime) | project TimeGenerated, Category, ResourceGroup, OperationName),
    (fn_src_mlp_ws_blkgrde("AzureDiagnostics", startTime, endTime) | project TimeGenerated, Category, ResourceGroup, OperationName)
};
