let fn_src_mlp_ws_blkgrde = (sourceType:string, startTime:datetime, endTime:datetime) {

  union isfuzzy=true
    (
      workspace("/subscriptions/c68213bf-7453-4ba4-9aaa-56b822af4c20/resourceGroups/MLP-PRD-RG-BLKGRDE/providers/Microsoft.OperationalInsights/workspaces/mlp-prd-law-blkgrde").table("AzureDiagnostics")
      | where TimeGenerated between (startTime .. endTime)
      | where sourceType == "AzureDiagnostics"
      | extend source_table = "AzureDiagnostics"
    )
};
