let fn_src_notpii_databricksjobs_all = (startTime:datetime, endTime:datetime) {
  union
    (workspace("/subscriptions/0d996eb2-802f-4ef8-8ae6-d385c74da7e6/resourceGroups/ams-dev-dataplatform-rg/providers/Microsoft.OperationalInsights/workspaces/ams-dev-dataplatform-laws").table("DatabricksJobs")
      | where TimeGenerated between (startTime .. endTime)
      | project TimeGenerated, RequestParams),
    (workspace("/subscriptions/0d996eb2-802f-4ef8-8ae6-d385c74da7e6/resourceGroups/ams-uat-dataplatform-rg/providers/Microsoft.OperationalInsights/workspaces/ams-uat-dataplatform-laws").table("DatabricksJobs")
      | where TimeGenerated between (startTime .. endTime)
      | project TimeGenerated, RequestParams)
};
