let fn_src_mlp_notpii_pisystem_consolelogs = (startTime:datetime, endTime:datetime) {
  workspace("/subscriptions/c68213bf-7453-4ba4-9aaa-56b822af4c20/resourceGroups/MLP-PRD-RG-PISYSTEM/providers/Microsoft.OperationalInsights/workspaces/mlp-prd-law-pisystem").table("ContainerAppConsoleLogs_CL")
  | where TimeGenerated between (startTime .. endTime)
  | project TimeGenerated, ContainerJobName_s, Log_s
};
