let fn_prd_mlp_notpii_dom_global_status = (startTime:datetime, endTime:datetime) {
  let autoloader_uat = iff(toscalar(fn_prd_mlp_notpii_dom_autoloader_uat_status(startTime, endTime) | project color) == "#E53935", "ALERT", "OK");
  let autoloader_dev = iff(toscalar(fn_prd_mlp_notpii_dom_autoloader_dev_status(startTime, endTime) | project color) == "#E53935", "ALERT", "OK");
  let ingesta = iff(toscalar(fn_prd_mlp_notpii_dom_ingesta_status(startTime, endTime) | project color) == "#E53935", "ALERT", "OK");
  print
    autoloader_uat = autoloader_uat,
    autoloader_dev = autoloader_dev,
    ingesta = ingesta
};
